// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKByLyNqZehGxs_vv59cY4t4ZnRVLaX28',
    appId: '1:110656260145:web:926e9ff4e7cdd72f85ad10',
    messagingSenderId: '110656260145',
    projectId: 'udemyfirebaseex',
    authDomain: 'udemyfirebaseex.firebaseapp.com',
    storageBucket: 'udemyfirebaseex.firebasestorage.app',
    measurementId: 'G-7KBL1373GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD54zW-yrkqUlxVk45tEk-W-rjEEZybBaI',
    appId: '1:110656260145:android:bd715df7389ce07f85ad10',
    messagingSenderId: '110656260145',
    projectId: 'udemyfirebaseex',
    storageBucket: 'udemyfirebaseex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQgac29e-XSgOLKQb8FQcINCshkC71dxo',
    appId: '1:110656260145:ios:7a7d9174279c802e85ad10',
    messagingSenderId: '110656260145',
    projectId: 'udemyfirebaseex',
    storageBucket: 'udemyfirebaseex.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEx',
  );
}
